//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace My_Soap_Service.Generated.Client.MySoapServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PersonResponse", Namespace="http://schemas.datacontract.org/2004/07/My_Soap_Service.Service.Responses")]
    [System.SerializableAttribute()]
    public partial class PersonResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CPFField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SituationField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CPF {
            get {
                return this.CPFField;
            }
            set {
                if ((object.ReferenceEquals(this.CPFField, value) != true)) {
                    this.CPFField = value;
                    this.RaisePropertyChanged("CPF");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Situation {
            get {
                return this.SituationField;
            }
            set {
                if ((object.ReferenceEquals(this.SituationField, value) != true)) {
                    this.SituationField = value;
                    this.RaisePropertyChanged("Situation");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PersonNotFoundFault", Namespace="http://schemas.datacontract.org/2004/07/My_Soap_Service.Service.Faults")]
    [System.SerializableAttribute()]
    public partial class PersonNotFoundFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompanyResponse", Namespace="http://schemas.datacontract.org/2004/07/My_Soap_Service.Service.Responses")]
    [System.SerializableAttribute()]
    public partial class CompanyResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CNPJField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SituationField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CNPJ {
            get {
                return this.CNPJField;
            }
            set {
                if ((object.ReferenceEquals(this.CNPJField, value) != true)) {
                    this.CNPJField = value;
                    this.RaisePropertyChanged("CNPJ");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Situation {
            get {
                return this.SituationField;
            }
            set {
                if ((object.ReferenceEquals(this.SituationField, value) != true)) {
                    this.SituationField = value;
                    this.RaisePropertyChanged("Situation");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompanyNotFoundFault", Namespace="http://schemas.datacontract.org/2004/07/My_Soap_Service.Service.Faults")]
    [System.SerializableAttribute()]
    public partial class CompanyNotFoundFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MySoapServiceReference.IValidationService")]
    public interface IValidationService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IValidationService/ValidateEmail", ReplyAction="http://tempuri.org/IValidationService/ValidateEmailResponse")]
        bool ValidateEmail(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IValidationService/ValidateEmail", ReplyAction="http://tempuri.org/IValidationService/ValidateEmailResponse")]
        System.Threading.Tasks.Task<bool> ValidateEmailAsync(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IValidationService/ValidateCPF", ReplyAction="http://tempuri.org/IValidationService/ValidateCPFResponse")]
        bool ValidateCPF(string cpf);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IValidationService/ValidateCPF", ReplyAction="http://tempuri.org/IValidationService/ValidateCPFResponse")]
        System.Threading.Tasks.Task<bool> ValidateCPFAsync(string cpf);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IValidationService/ValidateCNPJ", ReplyAction="http://tempuri.org/IValidationService/ValidateCNPJResponse")]
        bool ValidateCNPJ(string cnpj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IValidationService/ValidateCNPJ", ReplyAction="http://tempuri.org/IValidationService/ValidateCNPJResponse")]
        System.Threading.Tasks.Task<bool> ValidateCNPJAsync(string cnpj);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IValidationServiceChannel : My_Soap_Service.Generated.Client.MySoapServiceReference.IValidationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ValidationServiceClient : System.ServiceModel.ClientBase<My_Soap_Service.Generated.Client.MySoapServiceReference.IValidationService>, My_Soap_Service.Generated.Client.MySoapServiceReference.IValidationService {
        
        public ValidationServiceClient() {
        }
        
        public ValidationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ValidationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ValidationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ValidationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool ValidateEmail(string email) {
            return base.Channel.ValidateEmail(email);
        }
        
        public System.Threading.Tasks.Task<bool> ValidateEmailAsync(string email) {
            return base.Channel.ValidateEmailAsync(email);
        }
        
        public bool ValidateCPF(string cpf) {
            return base.Channel.ValidateCPF(cpf);
        }
        
        public System.Threading.Tasks.Task<bool> ValidateCPFAsync(string cpf) {
            return base.Channel.ValidateCPFAsync(cpf);
        }
        
        public bool ValidateCNPJ(string cnpj) {
            return base.Channel.ValidateCNPJ(cnpj);
        }
        
        public System.Threading.Tasks.Task<bool> ValidateCNPJAsync(string cnpj) {
            return base.Channel.ValidateCNPJAsync(cnpj);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MySoapServiceReference.ISearchService")]
    public interface ISearchService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearchService/SearchPersonByEmail", ReplyAction="http://tempuri.org/ISearchService/SearchPersonByEmailResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(My_Soap_Service.Generated.Client.MySoapServiceReference.PersonNotFoundFault), Action="http://tempuri.org/ISearchService/SearchPersonByEmailPersonNotFoundFaultFault", Name="PersonNotFoundFault", Namespace="http://schemas.datacontract.org/2004/07/My_Soap_Service.Service.Faults")]
        My_Soap_Service.Generated.Client.MySoapServiceReference.PersonResponse SearchPersonByEmail(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearchService/SearchPersonByEmail", ReplyAction="http://tempuri.org/ISearchService/SearchPersonByEmailResponse")]
        System.Threading.Tasks.Task<My_Soap_Service.Generated.Client.MySoapServiceReference.PersonResponse> SearchPersonByEmailAsync(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearchService/SearchByCPF", ReplyAction="http://tempuri.org/ISearchService/SearchByCPFResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(My_Soap_Service.Generated.Client.MySoapServiceReference.PersonNotFoundFault), Action="http://tempuri.org/ISearchService/SearchByCPFPersonNotFoundFaultFault", Name="PersonNotFoundFault", Namespace="http://schemas.datacontract.org/2004/07/My_Soap_Service.Service.Faults")]
        My_Soap_Service.Generated.Client.MySoapServiceReference.PersonResponse SearchByCPF(string cpf);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearchService/SearchByCPF", ReplyAction="http://tempuri.org/ISearchService/SearchByCPFResponse")]
        System.Threading.Tasks.Task<My_Soap_Service.Generated.Client.MySoapServiceReference.PersonResponse> SearchByCPFAsync(string cpf);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearchService/SearchCompanyByEmail", ReplyAction="http://tempuri.org/ISearchService/SearchCompanyByEmailResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(My_Soap_Service.Generated.Client.MySoapServiceReference.CompanyNotFoundFault), Action="http://tempuri.org/ISearchService/SearchCompanyByEmailCompanyNotFoundFaultFault", Name="CompanyNotFoundFault", Namespace="http://schemas.datacontract.org/2004/07/My_Soap_Service.Service.Faults")]
        My_Soap_Service.Generated.Client.MySoapServiceReference.CompanyResponse SearchCompanyByEmail(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearchService/SearchCompanyByEmail", ReplyAction="http://tempuri.org/ISearchService/SearchCompanyByEmailResponse")]
        System.Threading.Tasks.Task<My_Soap_Service.Generated.Client.MySoapServiceReference.CompanyResponse> SearchCompanyByEmailAsync(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearchService/SearchByCNPJ", ReplyAction="http://tempuri.org/ISearchService/SearchByCNPJResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(My_Soap_Service.Generated.Client.MySoapServiceReference.CompanyNotFoundFault), Action="http://tempuri.org/ISearchService/SearchByCNPJCompanyNotFoundFaultFault", Name="CompanyNotFoundFault", Namespace="http://schemas.datacontract.org/2004/07/My_Soap_Service.Service.Faults")]
        My_Soap_Service.Generated.Client.MySoapServiceReference.CompanyResponse SearchByCNPJ(string cnpj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearchService/SearchByCNPJ", ReplyAction="http://tempuri.org/ISearchService/SearchByCNPJResponse")]
        System.Threading.Tasks.Task<My_Soap_Service.Generated.Client.MySoapServiceReference.CompanyResponse> SearchByCNPJAsync(string cnpj);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISearchServiceChannel : My_Soap_Service.Generated.Client.MySoapServiceReference.ISearchService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SearchServiceClient : System.ServiceModel.ClientBase<My_Soap_Service.Generated.Client.MySoapServiceReference.ISearchService>, My_Soap_Service.Generated.Client.MySoapServiceReference.ISearchService {
        
        public SearchServiceClient() {
        }
        
        public SearchServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SearchServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SearchServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SearchServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public My_Soap_Service.Generated.Client.MySoapServiceReference.PersonResponse SearchPersonByEmail(string email) {
            return base.Channel.SearchPersonByEmail(email);
        }
        
        public System.Threading.Tasks.Task<My_Soap_Service.Generated.Client.MySoapServiceReference.PersonResponse> SearchPersonByEmailAsync(string email) {
            return base.Channel.SearchPersonByEmailAsync(email);
        }
        
        public My_Soap_Service.Generated.Client.MySoapServiceReference.PersonResponse SearchByCPF(string cpf) {
            return base.Channel.SearchByCPF(cpf);
        }
        
        public System.Threading.Tasks.Task<My_Soap_Service.Generated.Client.MySoapServiceReference.PersonResponse> SearchByCPFAsync(string cpf) {
            return base.Channel.SearchByCPFAsync(cpf);
        }
        
        public My_Soap_Service.Generated.Client.MySoapServiceReference.CompanyResponse SearchCompanyByEmail(string email) {
            return base.Channel.SearchCompanyByEmail(email);
        }
        
        public System.Threading.Tasks.Task<My_Soap_Service.Generated.Client.MySoapServiceReference.CompanyResponse> SearchCompanyByEmailAsync(string email) {
            return base.Channel.SearchCompanyByEmailAsync(email);
        }
        
        public My_Soap_Service.Generated.Client.MySoapServiceReference.CompanyResponse SearchByCNPJ(string cnpj) {
            return base.Channel.SearchByCNPJ(cnpj);
        }
        
        public System.Threading.Tasks.Task<My_Soap_Service.Generated.Client.MySoapServiceReference.CompanyResponse> SearchByCNPJAsync(string cnpj) {
            return base.Channel.SearchByCNPJAsync(cnpj);
        }
    }
}
